version: '3.8'

services:
  postgesql:
    image: postgres:12-alpine
    container_name: postgesql
    ports:
      - '5432:5432'
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=users
    networks:
      - web_api
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    container_name: api
    build:
      context: ./
      dockerfile: docker/Dockerfile
    ports:
      - '8080:8080'
    environment:
      - PORT=8080
    depends_on:
      postgesql:
        condition: service_healthy
    restart: always
    networks:
      - web_api

networks:
  web_api:
    driver: bridge
