server:
  Port: :8080
  ReadTimeout: 5
  WriteTimeout: 5

postgres:
  PostgresqlHost: localhost
  PostgresqlPort: 5432
  PostgresqlUser: user
  PostgresqlPassword: password
  PostgresqlDbname: users
  PostgresqlSslmode: false
  PgDriver: pgx